services:
  - type: web
    name: my-app
    runtime: node
    buildCommand: npm install; npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
databases:
  - name: my-database
    plan: free
